Improve affiliated package layout
sunpy/sunpy.org pull request #333
Opened 2022-09-02 14:41 UTC by dstansby

2022-09-02 14:50 UTC, dstansby commented
See https://deploy-preview-333--sunpy.netlify.app/project/affiliated for the preview

2022-09-02 14:54 UTC, nabobalis commented
Time to remove sponsored too and change the authors to be the sunpy community?

2022-09-02 15:04 UTC, nabobalis commented on project/affiliated.rst
>     * - **NDCube**
```suggestion
   * - **ndcube**
```

2022-09-02 15:05 UTC, nabobalis commented on project/affiliated.rst
> +       *Maintainers*: The SunPy Community
```suggestion
       **Maintainers**: The SunPy Community
```

2022-09-02 15:15 UTC, Cadair commented
>  as there isn't really such a thing as "provisional"

yes there [really is](https://sunpy.org/project/affiliated#review-criteria-and-summary), and they have to be reviewed to get there.

2022-09-02 15:17 UTC, dstansby commented
> > as there isn't really such a thing as "provisional"
> 
> yes there [really is](https://sunpy.org/project/affiliated#review-criteria-and-summary), and they have to be reviewed to get there.

Woops, my bad, I'll put these back

2022-09-02 15:20 UTC, Cadair commented on project/affiliated.rst
> +       **Maintainers**: The SunPy Community
I think project would be better in this context, but I am not 100 % sure.

2022-09-02 15:22 UTC, nabobalis commented on project/affiliated.rst
> +       **Maintainers**: The SunPy Community
As its only the "project members" who can tag a release, merge in PRs etc.

2022-09-02 15:36 UTC, nabobalis commented on project/affiliated.rst
> +     - A core package for solar physics in Python.
One day we will come up with a better phrase for this.

2022-09-07 08:17 UTC, nabobalis submitted a review, later dismissed

2022-09-07 08:29 UTC, Cadair requested changes
I have two things: [Nabil's comment](https://github.com/sunpy/sunpy.org/pull/333/files#r961788395) about community vs project is worth discussing, and along those lines I think it would be worth maybe putting a footnote or something deeper down the page about what exactly it means to be "maintained by sunpy"? One thing we could mention in that section is that we used to call these things "sponsored".

2022-09-07 08:31 UTC, nabobalis commented
Should we use coordinated instead of sponsored? 

If we are holding on changes, I will also do an authorship review of the packages as well.

2022-09-07 08:32 UTC, nabobalis commented on project/affiliated.rst
> +       **Maintainers**: `Will Barnes`_, `Mark Cheung`_, `Nabil Freij`_
```suggestion
       **Maintainers**: `Nabil Freij`_ and `Will Barnes`_

2022-09-07 08:33 UTC, nabobalis commented on project/affiliated.rst
> +       **Maintainers**: `David Pérez-Suárez`_, `Shane Maloney`_, `Nabil Freij`_,
```suggestion
       **Maintainers**: The SunPy Community.
```

Maybe?

2022-09-07 08:37 UTC, Cadair commented
> I also wonder if we want to consider a url for the "sunpy community/project" so a person can find someone to talk or email?

I think this is what I meant by some kind of explanation as to what this means. How to contact us would be an excellent thing to add to such a section.

2022-09-07 12:51 UTC, dstansby commented
Just had the same thought in parallel before reading the above comments! I guess eventually we want to point to the "Project members" after the governance restructure,  but for now we could point to https://sunpy.org/project/#community-roles for names/faces. For contact I'm not too sure - do we want a non-public contact option (ie. an email address that isn't a mailing list?), or our existing public channels sufficient for this? I'm not too sure myself.

2022-09-07 13:01 UTC, nabobalis commented
We could link them to the help page or wherever we store our comms channel list?

2022-09-12 13:13 UTC, dstansby commented
Updated this in response to comments. Could probably bikeshed this for a while longer, but I think this is an improvement worth merging at this point?

2022-09-12 13:23 UTC, Cadair approved these changes

2022-09-12 13:37 UTC, merged

2022-09-12 13:37 UTC, Cadair commented
> do we want a non-public contact option

In general no. I think that we should encourage open communication for us and for the other affiliated packages.